[package]
name = "book_service"
version = "0.1.0"
edition = "2024"
default-run = "app"

[[bin]]
name = "app"
path = "src/bin/app.rs"

[dependencies]
anyhow = "1.0.104"
axum = "0.8.9"
envconfig = "0.11.1"
tokio = { version = "1.53.1", features = ["full"] }
tower = "0.5.3"
tower-http = { version = "0.7.1", features = ["cors", "request-id", "trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["json", "env-filter"] }

[lint]
workspace = true
